config/routes.rb
FlatuiApp::Application.routes.draw do
  resources :uploaders

  get "/aboutus", to: 'static#aboutus'
  get "/ceremony", to: 'static#ceremony'
  get "/reception", to: 'static#reception'
  get "/accommodations", to: 'static#accommodations'
  get "/presents", to: 'static#presents'

  resources :sessions
  get "/admin", to: 'sessions#new'
  get "/signout", to: 'sessions#destroy'

  resources :admins

  resources :images

  resources :guests

  get '/admin-content', to: 'images#admin_content'
  post '/images_status', to: 'images#images_status'

  post '/mercado_pago', to: 'guests#mercado_pago'
  get "flatuipro_demo/index"

  match '/mercado_response' , to: 'guests#mercado_response', via:[:post,:get]

  root 'static#aboutus'

  

end

app/models/guest.rb
class Guest < ActiveRecord::Base
  DISHES = ['pato', 'res']

  before_validation :format_attributes, on: [:create, :update]

  has_one :guest, class_name: 'Guest', foreign_key: 'companion_id'
  belongs_to :companion, class_name: 'Guest', dependent: :destroy

  validates_presence_of :name, message:"Nombre es campo requerido."
  validates_presence_of :lastname, message:"Apellido(s) es campo requerido."

  validates_numericality_of :mobile, greater_than:0, :only_integer =>true, message:"Celular invalido"
  validates :mobile, length: { minimum: 10, maximum: 10, message:"Formato de 10 digitos." }

  validates :email,
          :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :allow_nil=>false, message:"Email invalido." }

  validates :dish, inclusion: {in:DISHES,message:"Selecciona un platillo."}


  accepts_nested_attributes_for :companion, allow_destroy: true


  def self.dishes
    [['Platillo','platillo'],['Pato','pato'], ['Res','res']]
  end

  protected
  def format_attributes
    ['name', 'lastname'].each do |name|
      name = name.to_sym
      self[name] = self[name].titleize
    end
    ['email','facebook', 'twitter', 'instagram'].each do |name|
      name = name.to_sym
      self[name] = self[name].downcase
    end
  end



end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  include ApplicationHelper

  before_action :set_guest, only: [:show, :edit, :update, :destroy]

  skip_before_action :verify_authenticity_token

  before_action :get_admin, except:[:new, :create, :mercado_pago, :mercado_response]

  # GET /guests
  # GET /guests.json
  def index
    @guests = Guest.all
    @total = @guests.count
    guests = @guests.dup.to_a
    @guests_with_companion = []
    @guests.each do |guest|
      unless guest.companion.nil?
        @guests_with_companion << guest
        guests.delete(guest)
        guests.delete(guest.companion)
      end
    end
    @guests = guests

    @dishes = Guest::DISHES
    @dishes_total = []
    @dishes.each do |dish|
      total = Guest.where(dish:dish).size
      @dishes_total << {dish:dish, total:total}
    end
  end

  # GET /guests/1
  # GET /guests/1.json
  def show
  end

  # GET /guests/new
  def new
    @guest = Guest.new
    @guest.build_companion
  end

  # GET /guests/1/edit
  def edit
    @companion = @guest.companion
    @plus_one =  nil
    @minus_one =  nil
    if @companion
      @plus_one = 'hidden'
      @minus_one = 'visible'
    end
  end

  # POST /guests
  # POST /guests.json
  def create
    @guest = Guest.new(guest_params)
    respond_to do |format|
      if @guest.save
        format.html { redirect_to @guest, notice: 'Guest was successfully created.' }
        format.json { render action: 'show', status: :created, location: @guest }
      else
        format.html { render action: 'new' }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guests/1
  # PATCH/PUT /guests/1.json
  def update
    respond_to do |format|

      unless @guest.companion_id.nil?
          unless guest_params[:companion_attributes]
            params[:guest][:companion_attributes] = { id: @guest.companion_id, _destroy: '1' }
          end
      end

      if @guest.update(guest_params)

        format.html { redirect_to @guest, notice: 'Guest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest.destroy
    respond_to do |format|
      format.html { redirect_to guests_url }
      format.json { head :no_content }
    end
  end


  def mercado_pago

    value = params[:value]

    dateTime = DateTime.now.strftime('%d%m%Y%H%M%S')
    client_id = '2267111060447384'
    client_secret = 'Wl7ZDdEsP8YewntOkXdE2ldfLNz5nLV7'

    if (session[:access_token])
        access_token = session[:access_token]
    else
      @authentication = HTTParty.post("https://api.mercadolibre.com/oauth/token", :headers => {'Accept' => 'application/json', 'Content-Type' => 'application/x-www-form-urlencoded' }, 
      :body => "grant_type=client_credentials&client_id=#{client_id}&client_secret=#{client_secret}" )

      access_token =  @authentication.parsed_response["access_token"]
      session[:access_token] = access_token
    end

    if session[:init_point]
      
      item = "{
                'items': [
                    {
                    'id': regalo_#{dateTime},
                    'title': 'Regalo Juan & Dulce',
                    'description': 'Regalo Juan & Dulce',
                    'quantity': 1,
                    'unit_price': #{value},
                    'currency_id': MXN,
                    'picture_url': 'https://www.mercadopago.com/org-img/MP3/home/logomp3.gif'
                    }
                ]
            }"
      @response = HTTParty.put("https://api.mercadolibre.com/checkout/preferences/#{session[:reference_id]}?access_token=#{access_token}", :headers => {'Accept' => 'application/json', 'Content-Type' => 'application/json' }, :body => item)
    else
      item = "{
                'items': [
                    {
                    'id': regalo_#{dateTime},
                    'title': 'Regalo Juan & Dulce',
                    'description': 'Regalo Juan & Dulce',
                    'quantity': 1,
                    'unit_price': #{value},
                    'currency_id': MXN,
                    'picture_url': 'https://www.mercadopago.com/org-img/MP3/home/logomp3.gif'
                    }
                ],
                'external_reference': 'reaglo_#{dateTime}',
                'back_urls': {
                    'success': '#{root_url}/presents?response=success',
                    'failure': '#{root_url}/presents?response=failure',
                    'pending': '#{root_url}/presents?response=pending'
                }
            }"

      @response = HTTParty.post("https://api.mercadolibre.com/checkout/preferences?access_token=#{access_token}", :headers => {'Header' => 'application/json', 'Content-Type' => 'application/json' }, :body => item)
      init_point =  @response.parsed_response["init_point"]
      reference_id =  @response.parsed_response["id"]
      session[:init_point] = init_point
      session[:reference_id] = reference_id


    end

    button = "<a id='payment-button' href='#{session[:init_point]}' name='MP-Checkout' class='lightblue-ar-s-ov' mp-mode='modal' onreturn='execute_my_onreturn'>Pagar</a><script type='text/javascript' src='http://mp-tools.mlstatic.com/buttons/render.js'></script></div>"

    respond_to do |format|
      format.json { render json: {response:@response.to_json, button:button }}
    end
    
  end

  def mercado_response
    respond_to do |format|
      format.json { render json: {status:200}}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest
      @guest = Guest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guest_params
      params.require(:guest).permit(:name, :lastname, :email, :mobile, :facebook, :twitter, :instagram, :dish, :companion_id, companion_attributes:[:name, :lastname, :email, :mobile, :facebook, :twitter, :instagram, :dish, :id, :_destroy])
    end
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_form.html.erb
<section id='thanks' class='well'>
  <h1>&iexcl;Gracias por acompañarnos!</h1>
  <img alt='star wars wedding' src='/assets/dulce_y_juan_thanks.jpg' />
</section>

<section id='rsvp_container' class='well clearfix'>
  <header>
    <h3>RSVP</h3>
  </header>
  <p>Te pedimos que reserves tu lugar antes del <strong>13 de Noviembre 2013</strong>.</p>
  <p>Para agregar un acompañante, da click a '+1'.</p>
  <section id='rsvp_form' class='well clearfix'>
    <%= form_for @guest, remote:true, :html=>{id:'guest_form'} do |f| %>
      <section id='guest'>
        <h4>Invitado</h4>
        <fieldset id='guest_personal_information'>
          <legend>Información Personal</legend>
            <div class='clearfix'>
              <div class='control-group'>
                <%=f.text_field :name,{placeholder:'Nombre', autofocus:'autofocus'}%>
              </div>
              <div class='control-group'>
                <%=f.text_field :lastname,{placeholder:'Apellido(s)'}%>
              </div>
              <div class='control-group'>
                <%=f.text_field :mobile,{placeholder:'Celular (10 dígitos)'}%>
              </div>
              <div class='control-group'>
                <%=f.text_field :email,{placeholder:'Email'}%>
              </div>
            </div>
            <p>Con tu información general, te contactamos en caso de cualquier acontecimiento.</p>
            
        </fieldset>
        <fieldset id='guest_social_information'>
          <legend>Información Social</legend>
          <div class='clearfix'>
            <div class='control-group'>
                <%=f.text_field :facebook,{placeholder:'Facebook'}%>
            </div>
            <div class='control-group'>
                <div class='input-prepend'>
                  <span class='add-on'>@</span>
                  <%=f.text_field :twitter,{placeholder:'Twitter',class:'span3'}%>
                </div>
            </div>
            <div class='control-group'>
                <div class='input-prepend'>
                  <span class='add-on'>@</span>
                  <%=f.text_field :instagram,{placeholder:'Instagram',class:'span3'}%>
                </div>
            </div>
          </div>
          <p>Con tu información social, veremos las fotos que tomes durante la boda.</p>

          <legend>Selecciona Platillo</legend>
            <div class='clearfix'>
              <div class='control-group'>
                 <%= f.select :dish, options_for_select(Guest.dishes,selected:(@guest.dish unless @guest.dish.nil?)),{},class:'info' %>
              </div>
            </div>
        </fieldset>
      </section>
      <section id='plus_one'>
        <%unless @guest.companion_id.nil? %>
          <h4>Adicional</h4>
          <fieldset id='plus_one_personal_information'>
            <legend>Información Personal</legend>
            <%=f.fields_for :companion do |c| %>
            <div class='clearfix'>
              <div class='control-group'>
                <%=c.text_field :name,{placeholder:'Nombre'}%>
              </div>
              <div class='control-group'>
                <%=c.text_field :lastname,{placeholder:'Apellido(s)'}%>
              </div>
              <div class='control-group'>
                <%=c.text_field :mobile,{placeholder:'Celular (10 dígitos)'}%>
              </div>
              <div class='control-group'>
                <%=c.text_field :email,{placeholder:'Email'}%>
              </div>
            </div>
          </fieldset>
          <fieldset id='plus_one_social_information'>
            <legend>Información Social</legend>
            <div class='clearfix'>
              <div class='control-group'>
                  <%=c.text_field :facebook,{placeholder:'Facebook'}%>
              </div>
              <div class='control-group'>
                <div class='input-prepend'>
                  <span class='add-on'>@</span>
                  <%=c.text_field :twitter,{placeholder:'Twitter',class:'span3'}%>
                </div>
              </div>
              <div class='control-group'>
                <div class='input-prepend'>
                  <span class='add-on'>@</span>
                  <%=c.text_field :instagram,{placeholder:'Instagram',class:'span3'}%>
                </div>
              </div> 
            </div>
            <legend>Selecciona Platillo</legend>
            <div class='clearfix'>
              <div class='control-group'>
                <%= c.select :dish, options_for_select(Guest.dishes, selected:(@guest.companion.dish unless @guest.companion.nil?)),{},class:'info' %>
              </div>
            </div>
          </fieldset>
          <%end%>
        <%end%>
      </section>
    <%end%>
  </section>

  <div id='plus_one_attributes'>
      <h4>Adicional</h4>
      <fieldset id='plus_one_personal_information'>
        <legend>Información Personal</legend>
        <div class='clearfix'>
          <div class='control-group'>
            <input type='text' placeholder='Nombre' name='guest[companion_attributes][name]' autofocus>
          </div>
          <div class='control-group'>
            <input type='text' placeholder='Apellido(s)' name='guest[companion_attributes][lastname]'>
          </div>
          <div class='control-group'>
            <input type='tel' placeholder='Celular (10 dígitos)' name='guest[companion_attributes][mobile]'>
          </div>
          <div class='control-group'>
            <input type='email' placeholder='Email' name='guest[companion_attributes][email]'>
          </div>
        </div>
      </fieldset>
      <fieldset id='plus_one_social_information'>
        <legend>Información Social</legend>
        <div class='clearfix'>
          <div class='control-group'>
            <input type='text' class='span3' placeholder='Facebook' name='guest[companion_attributes][facebook]' />
          </div>
          <div class='control-group'>
            <div class='input-prepend'>
              <span class='add-on'>@</span>
              <input type='text' class='span3' placeholder='Twitter' name='guest[companion_attributes][twitter]' />
            </div>
          </div>
          <div class='control-group'>
            <div class='input-prepend'>
              <span class='add-on'>@</span>
              <input type='text' class='span3' placeholder='Instagram' name='guest[companion_attributes][instagram]' />
            </div>
          </div> 
        </div>
      </fieldset>
      <legend>Selecciona Platillo</legend>
        <div class='clearfix'>
          <div class='control-group'>
            <%= select_tag 'guest[companion_attributes][dish]', options_for_select(Guest.dishes), class:'info' %>
          </div>
        </div>
  </div>

  <section class='buttons'>
    <input type='button' id='rsvp_submit' value='Enviar' class='btn btn-huge btn-primary'>
    <input type='button' id='plus_one_button' value='+1' class='btn btn-huge btn-warning <%=@plus_one%>'>
    <input type='button' id='minus_one_button' value='-1' class='btn btn-huge btn-warning <%=@minus_one%>'>
  </section>
</section>

app/views/guests/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @guest, class:'btn btn-info btn-large' %> |
<%= link_to 'Back', guests_path, class:'btn btn-large' %>

app/views/guests/index.html.erb
<div class='container'>
  <h3>Total: <%=@total%></h3>
  <h1>Guest with companion</h1>
  <table class='table table-striped'>
    <thead>
      <tr>
        <th>Name</th>
        <th>Lastname</th>
        <th>Email</th>
        <th>Mobile</th>
        <th>Facebook</th>
        <th>Twitter</th>
        <th>Instagram</th>
        <th>Dish</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @guests_with_companion.each do |guest| %>
        <tr>
          <td><%= guest.name %></td>
          <td><%= guest.lastname %></td>
          <td><%= guest.email %></td>
          <td><%= guest.mobile %></td>
          <td><%= guest.facebook %></td>
          <td><%= guest.twitter %></td>
          <td><%= guest.instagram %></td>
          <td><%= guest.dish %></td>
          <td>
          <div class="btn-group">
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
              Actions
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Show', guest %></li>
              <li><%= link_to 'Edit', edit_guest_path(guest) %></li>
              <li><%= link_to 'Destroy', guest, method: :delete, data: { confirm: 'Are you sure?' } %></li>
            </ul>
          </div>
        </td> 
        </tr>

        <tr>
          <td><%= guest.companion.name %></td>
          <td><%= guest.companion.lastname %></td>
          <td><%= guest.companion.email %></td>
          <td><%= guest.companion.mobile %></td>
          <td><%= guest.companion.facebook %></td>
          <td><%= guest.companion.twitter %></td>
          <td><%= guest.companion.instagram %></td>
          <td><%= guest.companion.dish %></td>
          <td></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <h1>Forever alone</h1>
  <table class='table'>
    <thead>
      <tr>
        <th>Name</th>
        <th>Lastname</th>
        <th>Email</th>
        <th>Mobile</th>
        <th>Facebook</th>
        <th>Twitter</th>
        <th>Instagram</th>
        <th>Dish</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @guests.each do |guest| %>
        <tr>
          <td><%= guest.name %></td>
          <td><%= guest.lastname %></td>
          <td><%= guest.email %></td>
          <td><%= guest.mobile %></td>
          <td><%= guest.facebook %></td>
          <td><%= guest.twitter %></td>
          <td><%= guest.instagram %></td>
          <td><%= guest.dish %></td>
          <td>
            <div class="btn-group">
              <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                Actions
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Show', guest %></li>
                <li><%= link_to 'Edit', edit_guest_path(guest) %></li>
                <li><%= link_to 'Destroy', guest, method: :delete, data: { confirm: 'Are you sure?' } %></li>
              </ul>
            </div>
          </td>          
        </tr>
      <% end %>
    </tbody>
  </table>
  <div id='dishes'>
    <h3>Dishes</h3>
    <% @dishes_total.each do |dish| %>
      <h4><%= "#{dish[:dish]} : #{dish[:total]}" %></h4>
    <%end%>
  </div>
</div>
<%= link_to 'New Guest', new_guest_path, class:'btn btn-info btn-large' %>

app/views/guests/new.html.erb
<%= render 'form' %>

app/views/guests/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Guest</h1>
<p>
  <strong>Name:</strong>
  <%= @guest.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @guest.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @guest.email %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @guest.mobile %>
</p>

<p>
  <strong>Facebook:</strong>
  <%= @guest.facebook %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @guest.twitter %>
</p>

<p>
  <strong>Instagram:</strong>
  <%= @guest.instagram %>
</p>

<p>
  <strong>Dish:</strong>
  <%= @guest.dish %>
</p>

<%if @guest.companion %>
<h1>Companion</h1>
<p>
  <strong>Name:</strong>
  <%= @guest.companion.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @guest.companion.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @guest.companion.email %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @guest.companion.mobile %>
</p>

<p>
  <strong>Facebook:</strong>
  <%= @guest.companion.facebook %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @guest.companion.twitter %>
</p>

<p>
  <strong>Instagram:</strong>
  <%= @guest.companion.instagram %>
</p>

<p>
  <strong>Dish:</strong>
  <%= @guest.companion.dish %>
</p>

<%end%>

<%= link_to 'Edit', edit_guest_path(@guest), class:'btn btn-info btn-large' %> |
<%= link_to 'Back', guests_path, class:'btn btn-large' %>