config/routes.rb
FlatuiApp::Application.routes.draw do
  resources :uploaders

  get "/aboutus", to: 'static#aboutus'
  get "/ceremony", to: 'static#ceremony'
  get "/reception", to: 'static#reception'
  get "/accommodations", to: 'static#accommodations'
  get "/presents", to: 'static#presents'

  resources :sessions
  get "/admin", to: 'sessions#new'
  get "/signout", to: 'sessions#destroy'

  resources :admins

  resources :images

  resources :guests

  get '/admin-content', to: 'images#admin_content'
  post '/images_status', to: 'images#images_status'

  post '/mercado_pago', to: 'guests#mercado_pago'
  get "flatuipro_demo/index"

  match '/mercado_response' , to: 'guests#mercado_response', via:[:post,:get]

  root 'static#aboutus'

  

end

app/models/uploader.rb
class Uploader < ActiveRecord::Base
  has_many :images

  accepts_nested_attributes_for :images
  before_validation :format_attributes, on: [:create, :update]

  validates_presence_of :name, message:"Nombre es campo requerido."
  validates_presence_of :lastname, message:"Apellido(s) es campo requerido."

  validates :email,
          :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :allow_nil=>false, message:"Email invalido." }


  protected
  def format_attributes
    ['name', 'lastname'].each do |name|
      name = name.to_sym
      self[name] = self[name].titleize
    end
    ['email'].each do |name|
      name = name.to_sym
      self[name] = self[name].downcase
    end
  end

end

app/controllers/uploaders_controller.rb
class UploadersController < ApplicationController
  include ApplicationHelper
  before_action :set_uploader, only: [:show, :edit, :update, :destroy]
  before_action :get_admin, except:[:new, :create]


  # GET /uploaders
  # GET /uploaders.json
  def index
    @uploaders = Uploader.all
  end

  # GET /uploaders/1
  # GET /uploaders/1.json
  def show
  end

  # GET /uploaders/new
  def new
    @uploader = Uploader.new
    @uploader.images.build
    @name = session[:name]
    @lastname = session[:lastname]
    @email = session[:email]
  end

  # GET /uploaders/1/edit
  def edit
  end

  # POST /uploaders
  # POST /uploaders.json
  def create
    @uploader = Uploader.find_or_initialize_by(email:uploader_params[:email])

    if @uploader.new_record?
      @uploader.attributes = uploader_params
    else
      @uploader.attributes = {images_attributes:uploader_params[:images_attributes]}
    end

    respond_to do |format|
      if @uploader.save
        session[:name] = @uploader.name
        session[:lastname] = @uploader.lastname
        session[:email] = @uploader.email
        format.html { redirect_to new_uploader_path, notice: '¡Gracias por subir tus fotos!.  En cuanto las aprobemos aparecerán en esta página.' }
        format.json { render action: 'show', status: :created, location: @uploader }
      else
        format.html { render action: 'new' }
        format.json { render json: @uploader.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uploaders/1
  # PATCH/PUT /uploaders/1.json
  def update
    respond_to do |format|
      if @uploader.update(uploader_params)
        format.html { redirect_to @uploader, notice: 'Uploader was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @uploader.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploaders/1
  # DELETE /uploaders/1.json
  def destroy
    @uploader.destroy
    respond_to do |format|
      format.html { redirect_to uploaders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_uploader
      @uploader = Uploader.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def uploader_params
      params.require(:uploader).permit(:name, :lastname, :email, images_attributes:[:photo, :tag_list])
    end
end

app/helpers/uploaders_helper.rb
module UploadersHelper
end

app/views/uploaders/_form.html.erb
<section id='rsvp_container' class='well clearfix'>
<%= form_for @uploader,:html => {:multipart => true} do |f| %>
  <% if @uploader.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@uploader.errors.count, "error") %> prohibited this uploader from being saved:</h2>

      <ul>
      <% @uploader.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

      <section id='guest'>
        <fieldset id='guest_personal_information'>
          <legend>&iquest;Qui&eacute;n sube las fotos?</legend>
          <div class='clearfix'>
            <div class="control-group">
              <%= f.text_field :name,{placeholder:'Nombre',value:@name, autofocus:'autofocus'} %>
            </div>
            <div class="control-group">
              <%= f.text_field :lastname,{placeholder:'Apellido(s)', value:@lastname} %>
            </div>
            <div class="control-group">
              <%= f.text_field :email,{placeholder:'Email',value:@email} %>
            </div>
          </div>
        </fieldset>
      </section>


  <div id='photos-container'>
    <legend>Selecciona tus fotos y agrégales tags.  Por ejemplo, si es una foto de Juan en su infancia, agrega estos tags: <span class='btn btn-primary'>juan</span> <span class='btn btn-primary'>infancia</span></legend>
    <div class='picture-container'>
      <div class='field'>
        <input title='Seleccionar Foto' id='main-photo' name='uploader[images_attributes][][photo]' class='photos btn btn-info' type='file' />
      </div>
      <input name="uploader[images_attributes][][tag_list]" class="tagsinput tagsinput-primary" value="juan, tabasco" />
    </div>

  </div>

  <div class='field'>
    <a  id='add-photo' class='btn btn-success'>
      <i class='icon-plus'></i>
      Agregar Foto
    </a>
  </div>

  <div class="actions" style='text-align:center'>
    <%= f.submit 'Subir Fotos', class:'btn btn-info btn-large' %>
  </div>
<% end %>
</section>

app/views/uploaders/edit.html.erb
<h1>Editing uploader</h1>

<%= render 'form' %>

<%= link_to 'Show', @uploader %> |
<%= link_to 'Back', uploaders_path %>

app/views/uploaders/index.html.erb
<h1>Listing uploaders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @uploaders.each do |uploader| %>
      <tr>
        <td><%= uploader.name %></td>
        <td><%= uploader.lastname %></td>
        <td><%= uploader.email %></td>
        <td><%= link_to 'Show', uploader %></td>
        <td><%= link_to 'Edit', edit_uploader_path(uploader) %></td>
        <td><%= link_to 'Destroy', uploader, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Uploader', new_uploader_path %>

app/views/uploaders/new.html.erb
<%= render 'form' %>

app/views/uploaders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @uploader.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @uploader.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @uploader.email %>
</p>

<%= link_to 'Edit', edit_uploader_path(@uploader) %> |
<%= link_to 'Back', uploaders_path %>