config/routes.rb
FlatuiApp::Application.routes.draw do
  resources :uploaders

  get "/aboutus", to: 'static#aboutus'
  get "/ceremony", to: 'static#ceremony'
  get "/reception", to: 'static#reception'
  get "/accommodations", to: 'static#accommodations'
  get "/presents", to: 'static#presents'

  resources :sessions
  get "/admin", to: 'sessions#new'
  get "/signout", to: 'sessions#destroy'

  resources :admins

  resources :images

  resources :guests

  get '/admin-content', to: 'images#admin_content'
  post '/images_status', to: 'images#images_status'

  post '/mercado_pago', to: 'guests#mercado_pago'
  get "flatuipro_demo/index"

  match '/mercado_response' , to: 'guests#mercado_response', via:[:post,:get]

  root 'static#aboutus'

  

end

app/models/image.rb
class Image < ActiveRecord::Base
  has_many :image_tags
  has_many :tags, through: :image_tags
  belongs_to :uploader

  has_attached_file :photo
  validates_attachment_content_type :photo, :content_type => /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/, :message => 'file type is not allowed (only jpeg/png/gif images)'
  
  after_save :set_tags

  def tag_list
    @tags
  end

  def tag_list=(tag_list)
    @tags = tag_list.split(',')
  end


  private
  def set_tags
    if @tags
      @tags.each do |tag|
        @tag = Tag.find_or_create_by_name(tag)
        self.tags << @tag
      end
    end
  end


end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  include ApplicationHelper
  skip_before_action :verify_authenticity_token
  before_action :set_image, only: [:show, :edit, :update, :destroy]


  # GET /images
  # GET /images.json
  def index
    @images = get_approved
    @left_images = []
    @right_images = []
    @center_images = []
    counter = 0
    @images.each do |image|
      counter+=1
      if counter == 1
        @left_images << image
      elsif counter ==2
        @center_images << image
      elsif counter ==3
        counter = 0
        @right_images << image
      end
    end
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
    @im
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render action: 'show', status: :created, location: @image }
      else
        format.html { render action: 'new' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :no_content }
    end
  end

  def images_status
    @images = params[:content]

    if @images
      @images.each do |key, image|
        @image = Image.find(image[:id])

        if image[:approved] == 'on'
          @image.update_attributes(approved: true)
        elsif
          @image.update_attributes(approved: false)
        end
      end
    end

    redirect_to '/admin-content'
  end

  def admin_content
    approved = params[:approved]

    if approved == "true"
      @images = get_approved
      @approved_flag = true
    else
      @images = get_not_approved
      @approved_flag = false
    end

    @left_images = []
    @right_images = []
    @center_images = []
    counter = 0
    @total_counter = 0
    @images.each do |image|
      counter+=1
      if counter == 1
        @left_images << image
      elsif counter ==2
        @center_images << image
      elsif counter ==3
        counter = 0
        @right_images << image
      end
    end
  end

  private

    def get_approved
      Image.where(approved: true)
    end

    def get_not_approved
      Image.where(approved: false)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:approved, :photo, :tag_list)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.file_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/admin_content.html.erb
<div class='share-photos'>
  <h1>Content Admin </h1>
  <ul class="nav nav-pills">
    <li <% unless @approved_flag %> class="active" <%end%> ><%= link_to 'Por Revisar', 'admin-content' %></li>
    <li <% if @approved_flag %> class="active" <%end%>><%= link_to 'Aprobados', 'admin-content?approved=true' %></li>
</ul>
</div>

<form action='/images_status' method='post' id='content-admin'>
<div id='gallery' class='well clearfix'>

  <div class='align-center'>
    <% if @images.count < 1%>
      <% if @approved_flag %>
        <h2>No hay imagenes aprobadas.</h2>
      <%else%>
        <h2>No hay imagenes por aprobar.</h2>
      <%end%>
    <%end%>
  </div>

  <div class='column left-column'>
    <%@left_images.each do |image|
      @total_counter+=1
    %>

      <div class='image-actions'>
        <div class='actions-section'>
          <div class='image-opacity'></div>
          <div class='actions-content clearfix'>
            <input name='content[<%=@total_counter%>][approved]' class='checkbox' type="checkbox" data-toggle='switch' <% if @approved_flag %> checked <%end%> >
            <input name='content[<%=@total_counter%>][id]' type='hidden' value='<%=image.id%>' />
          </div>
        </div>
          <%=image_tag image.photo.url%>
      </div>
    <%end%>
  </div>
  <div class='column center-column '>
      <%@center_images.each do |image|
        @total_counter+=1
      %>
        <div class='image-actions'>
          <div class='actions-section'>
            <div class='image-opacity'></div>
            <div class='actions-content clearfix'>
            <input name='content[<%=@total_counter%>][approved]' class='checkbox' type="checkbox" data-toggle='switch' <% if @approved_flag %> checked <%end%>>
            <input name='content[<%=@total_counter%>][id]' type='hidden' value='<%=image.id%>' />
            </div>
          </div>
            <%=image_tag image.photo.url%>
        </div>
      <%end%>
  </div>
  <div class='column right-column'>
    <%@right_images.each do |image|
      @total_counter+=1
    %>
      <div class='image-actions'>
        <div class='actions-section'>
          <div class='image-opacity'></div>
          <div class='actions-content clearfix'>
            <input name='content[<%=@total_counter%>][approved]' class='checkbox' type="checkbox" data-toggle='switch' <% if @approved_flag %> checked <%end%>>
            <input name='content[<%=@total_counter%>][id]' type='hidden' value='<%=image.id%>' />
          </div>
        </div>
          <%=image_tag image.photo.url%>
      </div>
    <%end%>
</div>
</div>
<div class='share-photos align-center'>
  <input type='submit' value='Guardar' class='btn btn-info btn-large' />
</div>

</form>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<div class='share-photos'>
  <%=link_to 'Comparte tus Fotos', '/uploaders/new', class:'btn btn-info btn-large'  %>
</div>

<div id='gallery' class='well clearfix'>
  <div class='column left-column'>
    <%@left_images.each do |image|%>
      <a class='photo-frame' alt="Juan & Dulce" href='<%=image.photo.url%>' target='_blank'>
        <%=image_tag image.photo.url%>
        <div class='photo-info'>
          <span class='opacity'></span>
          <span class='photo-by'>Por: <%=image.uploader.name%> <%=image.uploader.lastname%></span>
        </div>
      </a>
    <%end%>
  </div>
  <div class='column center-column'>
    <%@center_images.each do |image|%>
      <a class='photo-frame' alt="Juan & Dulce" href='<%=image.photo.url%>' target='_blank'>
        <%=image_tag image.photo.url%>
        <div class='photo-info'>
          <span class='opacity'></span>
          <span class='photo-by'>Por: <%=image.uploader.name%> <%=image.uploader.lastname%></span>
        </div>
      </a>
    <%end%>
  </div>
  <div class='column right-column'>
    <%@right_images.each do |image|%>
      <a class='photo-frame' alt="Juan & Dulce" href='<%=image.photo.url%>' target='_blank'>
        <%=image_tag image.photo.url%>
        <div class='photo-info'>
          <span class='opacity'></span>
          <span class='photo-by'>Por: <%=image.uploader.name%> <%=image.uploader.lastname%></span>
        </div>
      </a>
    <%end%>
  </div>
</div>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @image.title %>
</p>

<p>
  <strong>Name:</strong>
  <%= @image.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @image.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @image.email %>
</p>

<p>
  <strong>Approved:</strong>
  <%= @image.approved %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>